#!/usr/bin/env bash
# vim: set ft=sh :
#
# Git Graph
#
# Author: yesmeck@gmail.com
#
# License: MIT
#


dot_dir=$HOME/.git-graph

mkdir $dot_dir > /dev/null 2>&1

database=$dot_dir/data

now=$(date '+%Y-%m-%d %H:%I:%S')

location=$(CoreLocationCLI --once  2>/dev/null | grep -o '<+.*,+.*>' | sed 's/[<\+>]//g')

echo "INSERT INTO commits(location, created_at) VALUES ('${location}', '${now}');" | sqlite3 $database

