#!/usr/bin/env bash
# vim: set ft=sh :
#
# Git Graph
#
# Author: yesmeck@gmail.com
#
# License: MIT
#

dot_dir=$HOME/.git-graph
database=$dot_dir/data

if [[ ! -f $database  ]]; then
  mkdir $dot_dir > /dev/null 2>&1
  echo "CREATE TABLE commits(id INTEGER PRIMARY KEY, location TEXT, created_at TEXT);" | sqlite3 $database
fi

now=$(date '+%Y-%m-%d %H:%I:%S')

location=$(CoreLocationCLI --once  2>/dev/null | grep -o '<+.*,+.*>' | sed 's/[<\+>]//g')

echo "INSERT INTO commits(location, created_at) VALUES ('${location}', '${now}');" | sqlite3 $database

